### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by sandeshjatla** [armiro/Energy-Consumption-in-EV#2]
Can you please post the requirements along with the version numbers?
I am currently getting some errors.
Example:  
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 40: invalid continuation byte (line 63)
TypeError: __init__() got an unexpected keyword argument 'categorical_features' (line 90)

**Comment by itrack** [comment]
Hi,
The 'categorical_features' keyword is deprecated in version klearn 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
